[project]
name = "edda"

[bin]
main = "src/Main.saga"

[library]
module = "Edda"
expose = ["Edda", "Edda.Crypto", "Edda.Json", "Edda.Spec"]

[deps]
saga_http = { path = "../saga_http" }
saga_json = { path = "../saga_json" }
